const REACT_APP_BASE_DOMAIN_WITH_PROTOCOL = process.env.REACT_APP_BASE_DOMAIN_WITH_PROTOCOL;
const REACT_APP_BASE_WEB_DOMAIN_WITH_PROTOCOL = REACT_APP_BASE_DOMAIN_WITH_PROTOCOL || 'http://localhost:3003';
const REACT_APP_BASE_API_DOMAIN_WITH_PROTOCOL = REACT_APP_BASE_DOMAIN_WITH_PROTOCOL || 'http://localhost:4003';
exports.REACT_APP_BASE_WEB_PATH = process.env.REACT_APP_BASE_WEB_PATH || '';
exports.REACT_APP_BASE_SERVER_PATH = process.env.REACT_APP_BASE_SERVER_PATH || '';
exports.REACT_APP_BASE_WEB_URL = `${REACT_APP_BASE_WEB_DOMAIN_WITH_PROTOCOL}${exports.REACT_APP_BASE_WEB_PATH}`;
exports.REACT_APP_BASE_API_URL = `${REACT_APP_BASE_API_DOMAIN_WITH_PROTOCOL}${exports.REACT_APP_BASE_SERVER_PATH}`;
exports.REACT_APP_MAIN_URL = process.env.REACT_APP_MAIN_URL || 'http://localhost:3000';
