const REACT_APP_BASE_DOMAIN_WITH_PROTOCOL = process.env.REACT_APP_BASE_DOMAIN_WITH_PROTOCOL;
const REACT_APP_BASE_SERVER_PATH = process.env.REACT_APP_BASE_SERVER_PATH || '/api/dorms';
const REACT_APP_BASE_WEB_PATH = process.env.REACT_APP_BASE_WEB_PATH || '/dorms';
exports.REACT_APP_BASE_WEB_PATH = REACT_APP_BASE_WEB_PATH;
exports.REACT_APP_BASE_API_URL = `${REACT_APP_BASE_DOMAIN_WITH_PROTOCOL}${REACT_APP_BASE_SERVER_PATH}`;