const NEXT_PUBLIC_BASE_DOMAIN_WITH_PROTOCOL = process.env.NEXT_PUBLIC_BASE_DOMAIN_WITH_PROTOCOL;
const NEXT_PUBLIC_BASE_SERVER_PATH = process.env.NEXT_PUBLIC_BASE_SERVER_PATH || '/api';
const NEXT_PUBLIC_BASE_WEB_PATH = process.env.NEXT_PUBLIC_BASE_WEB_PATH || '';
exports.NEXT_PUBLIC_BASE_WEB_PATH = NEXT_PUBLIC_BASE_WEB_PATH;
exports.NEXT_PUBLIC_BASE_API_URL = `${NEXT_PUBLIC_BASE_DOMAIN_WITH_PROTOCOL}${NEXT_PUBLIC_BASE_SERVER_PATH}`;
exports.NEXT_PUBLIC_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
exports.NEXT_PUBLIC_SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
exports.NEXT_PUBLIC_BASE_WEB_URL = `${NEXT_PUBLIC_BASE_DOMAIN_WITH_PROTOCOL}${NEXT_PUBLIC_BASE_WEB_PATH}`;